### Testing getAllUsers
GET http://localhost:8080/users

### Testing getUserByEmail
GET http://localhost:8080/users/sarahso@gmail.com

### Testing createNewUser 
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "userName": "testingUser1",
    "email": "testingUser1@gmail.com",
    "password": "testingUser1!"
}

### Testing updateUser
PUT http://localhost:8080/users/testingUser1@gmail.com HTTP/1.1
content-type: application/json

{
    "userName": "testingUser2",
    "email": "testingUser2@gmail.com",
    "password": "testingUser2!"
}

### Testing deleteUser
DELETE http://localhost:8080/users/testingUser2@gmail.com HTTP/1.1
content-type: application/json




### Testing getAllFirstAidItems
GET http://localhost:8080/firstAid

### Testing getFirstAidItemByName
GET http://localhost:8080/firstAid/Band-aid

### Testing createNewFirstAidItem 
POST http://localhost:8080/firstAid HTTP/1.1
content-type: application/json

{
    "name": "Band-aid",
    "quantity": "12",
    "purchaseDate": "11/12/2022"
}

### Testing updateFirstAidItem
PUT http://localhost:8080/firstAid/Band-aid HTTP/1.1
content-type: application/json

{
    "name": "Band-aids",
    "quantity": "24",
    "purchaseDate": "11/13/2022"
}

### Testing deleteFirstAidItem
DELETE http://localhost:8080/firstAid/Band-aids HTTP/1.1
content-type: application/json